# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x11111bff
rootcolor = 0x1e1e2eff
bordercolor = 0x646789ff
focuscolor = 0xb4befeff
maximizescreencolor = 0xf5bde6ff
urgentcolor = 0xf38ba8ff
scratchpadcolor = 0xc6a0f6ff
globalcolor = 0x0123ffff
overlaycolor = 0xf10fb4ff
