# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x17111bff
bordercolor = 0x6d5b76ff
focuscolor = 0xacc7ffff
maximizescreencolor = 0xbb9af7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe0b8f6ff
globalcolor = 0x0051f9ff
overlaycolor = 0x4f00deff
