# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x17111bff
bordercolor = 0x9b8ba1ff
focuscolor = 0xadc6ffff
maximizescreencolor = 0xadc6ffff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe0b8f6ff
globalcolor = 0x0e448eff
overlaycolor = 0x2b4678ff
