[bar.default]
background_opacity = 0.69999998435378075
center = [ "workspaces" ]
end = [
    "sysmon",
    "spacer_2",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session",
    "clock"
]
margin_edge = 0
margin_ends = 0
radius = 10
start = [ "launcher" ]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 3600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 14400.0

[location]
address = "hooksett, nh"

[shell]
app_icon_color = "secondary"
app_icon_colorize = true
settings_show_advanced = true

[theme]
builtin = "Tokyo-Night"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "obsidian", "vscode", "zed", "vicinae", "steam" ]

[wallpaper]
directory = "/home/joe/.local/share/wallpapers"

    [wallpaper.default]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

    [wallpaper.last]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

[widget.spacer_2]
length = 60
type = "spacer"
