config_version = 8

[location]
address = "hooksett, nh"

[shell]
app_icon_color = "secondary"
app_icon_colorize = true
settings_show_advanced = true
font_family = "Inter"

[bar.default]
end = [
    "sysmon",
    "spacer_2",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session",
    "clock",
    "widget"
]
start = [ "launcher", "wallhaven" ]

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1235.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 0.79000000000000004
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_session_buttons = true

[plugin_settings."yuuto/arch-updater"]
aur_helper = "yay"
auto_check_hours = 4
terminal = "ghostty"

[plugins]
enabled = [ "noctalia/wallhaven", "yuuto/arch-updater" ]

[widget.spacer_2]
length = 60
type = "spacer"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.widget]
hide_on_empty = true
type = "yuuto/arch-updater:widget"
