[bar.default]
background_opacity = 0.69999998435378075
center = [ "workspaces" ]
end = [
    "sysmon",
    "spacer_2",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session",
    "clock"
]
margin_edge = 0
margin_ends = 0
radius = 10
start = [ "launcher" ]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 3600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 14400.0

[location]
address = "hooksett, nh"

[lockscreen_widgets]
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@DP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1080.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1080.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 431.5
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = false
        clock_style = "digital"
        color = "primary"

[shell]
app_icon_color = "secondary"
app_icon_colorize = true
settings_show_advanced = true

[theme]
builtin = "Tokyo-Night"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "obsidian", "vscode", "zed", "vicinae", "steam" ]

[wallpaper]
directory = "/home/joe/.local/share/wallpapers"

    [wallpaper.default]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

    [wallpaper.last]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/joe/.local/share/wallpapers/BlueGalaxy.jpg"

[widget.spacer_2]
length = 60
type = "spacer"
